### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ousamabenyounes** [davidruffner/monti-time-logger#1]
monti-time-logger/gmailInfo_Template.yml  file has been compromised and your login/pwd are now visible on this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

Hope this will help you :)

**Comment by davidruffner** [comment]
Ah great catch! I will remove it. I've changed the login/pwd on my projects
as well. I appreciate the tip.

**Comment by davidruffner** [comment]
I removed the files with BFG.  Thanks again for the catch.

**Comment by ousamabenyounes** [comment]
it is a pleasure to help other developers ...
Good luck for your project and be sure that sensioInsight project will helps you discover lot of things.

I learned lot of things with it...
And it works for you if one of your depedency contains some known security issue, it will alert you..

Regards,
Ousama.
